services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./csv-backend/.env
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=True
    volumes:
      - sqlite_data:/app
      - media_data:/app/media
    restart: unless-stopped

volumes:
  sqlite_data:
  media_data:
